# Generated by Django 5.0.4 on 2024-04-25 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente', '0002_client_groupe_mesure_commande_mesureproduit_paiement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantite_initiale', models.FloatField(editable=False, null=True)),
                ('quantite_actuelle', models.FloatField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delai_expiration', models.PositiveIntegerField()),
                ('prix', models.FloatField()),
                ('produitt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vente.produit')),
            ],
        ),
    ]
