# Generated by Django 5.0.4 on 2024-04-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente', '0003_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='produitt',
            new_name='produit',
        ),
        migrations.AlterField(
            model_name='stock',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
